In [2]:
import pandas as pd

In [2]:
pd.__version__

'0.21.0'

In [31]:
Yeast_10_6_order_10ul_x5 = pd.read_csv('Yeast_10_6_order_10ul_x10.csv',low_memory=False)

In [33]:
Yeast_10_6_order_10ul_x5.shape

(4098, 3599)

In [18]:
tempSample = Yeast_10_6_order_10ul_x5.loc[1:, ['Unnamed: 1','Unnamed: 4','Unnamed: 7','Unnamed: 10']]

In [19]:
tempSample

Unnamed: 1             Unnamed: 4     Unnamed: 7  \
1     Terahertz signal (a.u.)  Electric field (a.u.)  Transmittance   
2                 -0.01804322                6.88203       2.673557   
3                 -0.02111875              0.6927925      0.2033236   
4                 -0.01681809              0.8349739       1.401699   
5                 -0.02208075               1.920209      0.8537656   
6                 -0.02494478               3.712943      0.7183219   
7                 -0.02022591                5.51333      0.7679713   
8                 -0.02351194               6.496024      0.8877195   
9                 -0.02092568                6.40656      0.9930028   
10                -0.02455329               5.740438      0.9894645   
11                -0.02123577               5.192579      0.9435052   
12                -0.02220568               4.995144      0.9972789   
13                -0.02519521               4.863997       1.146931   
14                -0.02504743               4.512341       1.232338   
15                -0.02777996               4.030838       1.165307   
16                -0.02969043               3.702827       1.108804   
17                -0.02968067               3.599897       1.154027   
18                 -0.0292097               3.525848       1.181751   
19                -0.02725679               3.321596       1.092012   
20                -0.02839914               3.060353      0.9945492   
21                -0.02548743               2.896707       0.984663   
22                -0.02620553               2.849893      0.9978882   
23                -0.02717838               2.833083      0.9262491   
24                -0.03002304               2.824488      0.8256204   
25                -0.02735112               2.890148      0.7839248   
26                -0.03242309               3.049514      0.7809075   
27                -0.02514157               3.227363      0.7485204   
28                 -0.0271321               3.371491      0.6883949   
29                 -0.0328542                3.53616      0.6510038   
30                -0.03128776               3.790514      0.6450443   
...                       ...                    ...            ...   
4068             -0.007898049                    NaN            NaN   
4069               -0.0118013                    NaN            NaN   
4070             -0.009110876                    NaN            NaN   
4071              -0.01109779                    NaN            NaN   
4072             -0.009834031                    NaN            NaN   
4073              -0.01050237                    NaN            NaN   
4074              -0.01577201                    NaN            NaN   
4075             -0.008814468                    NaN            NaN   
4076              -0.01551837                    NaN            NaN   
4077              -0.01195459                    NaN            NaN   
4078              -0.01381432                    NaN            NaN   
4079              -0.01382722                    NaN            NaN   
4080              -0.00920059                    NaN            NaN   
4081               -0.0133783                    NaN            NaN   
4082               -0.0159682                    NaN            NaN   
4083               -0.0112609                    NaN            NaN   
4084             -0.008915353                    NaN            NaN   
4085              -0.01721862                    NaN            NaN   
4086             -0.008181388                    NaN            NaN   
4087             -0.008577848                    NaN            NaN   
4088             -0.007860034                    NaN            NaN   
4089             -0.009088007                    NaN            NaN   
4090              -0.01273255                    NaN            NaN   
4091              -0.00594209                    NaN            NaN   
4092              -0.01000044              

In [22]:
tempSample2 = Yeast_10_6_order_10ul_x5.loc[1:, ['Unnamed: '+str(12+1),'Unnamed: '+str(12+4),'Unnamed: '+str(12+7),'Unnamed: '+str(12+10)]]

In [23]:
tempSample2

Unnamed: 13            Unnamed: 16    Unnamed: 19  \
1     Terahertz signal (a.u.)  Electric field (a.u.)  Transmittance   
2                 -0.01692473               8.243268       3.202376   
3                 -0.01896029              0.4981646      0.1462034   
4                 -0.02148728              0.9074199       1.523316   
5                 -0.02227795               1.951185      0.8675381   
6                 -0.02154227               3.586228      0.6938072   
7                   -0.019872               5.357868      0.7463164   
8                 -0.02207304               6.485383      0.8862653   
9                 -0.02153404               6.511393       1.009252   
10                 -0.0218951               5.792629      0.9984605   
11                -0.02695641               5.137562      0.9335086   
12                -0.02353733               4.943969      0.9870619   
13                -0.02693465               4.899297       1.155255   
14                -0.02767124               4.572535       1.248778   
15                -0.02891693               4.030618       1.165244   
16                -0.02465658                3.66709       1.098103   
17                -0.02016068               3.604658       1.155554   
18                -0.02750373               3.571234       1.196963   
19                 -0.0269972               3.347324        1.10047   
20                -0.02471616               3.054952       0.992794   
21                -0.02687373               2.908876      0.9887996   
22                -0.02790506               2.897199       1.014452   
23                -0.03004761               2.873446      0.9394456   
24                -0.03130407               2.832266       0.827894   
25                -0.03102396               2.898217      0.7861135   
26                -0.03466211               3.088258      0.7908289   
27                -0.03127083               3.271802      0.7588271   
28                -0.02792052               3.385932      0.6913435   
29                -0.02997017               3.533348      0.6504861   
30                -0.02883119                 3.8023      0.6470498   
...                       ...                    ...            ...   
4068             -0.008380928                    NaN            NaN   
4069              -0.01288034                    NaN            NaN   
4070             -0.008613342                    NaN            NaN   
4071             -0.009516522                    NaN            NaN   
4072             -0.006512431                    NaN            NaN   
4073              -0.01383828                    NaN            NaN   
4074             -0.009673131                    NaN            NaN   
4075              -0.01349092                    NaN            NaN   
4076              -0.01443065                    NaN            NaN   
4077              -0.01536855                    NaN            NaN   
4078              -0.01260915                    NaN            NaN   
4079             -0.009029053                    NaN            NaN   
4080              -0.01225477                    NaN            NaN   
4081              -0.01494316                    NaN            NaN   
4082              -0.01490566                    NaN            NaN   
4083             -0.008136652                    NaN            NaN   
4084              -0.01592652                    NaN            NaN   
4085              -0.01062831                    NaN            NaN   
4086              -0.01121095                    NaN            NaN   
4087               -0.0132284                    NaN            NaN   
4088             -0.008167427                    NaN            NaN   
4089              -0.01218508                    NaN            NaN   
4090             -0.008921511                    NaN            NaN   
4091             -0.008595582                    NaN            NaN   
4092             -0.009316836             

In [3]:
ser1 = pd.Series([1, 2, 3], ["a","b","c"])

In [4]:
ser1

a    1
b    2
c    3
dtype: int64

In [6]:
ser1.last

<bound method NDFrame.last of a    1
b    2
c    3
dtype: int64>

In [7]:
import numpy.random as rd

In [11]:
df = pd.DataFrame(rd.randn(3,3), ['A', 'B', 'C'], ['X', 'Y', 'Z'])

In [12]:
df

X         Y         Z
A -0.079689  0.330638  0.391180
B  1.047661 -0.144868  0.201546
C  0.204755  1.294356  1.425724

In [16]:
df[['Y', 'Z']]

Y         Z
A  0.330638  0.391180
B -0.144868  0.201546
C  1.294356  1.425724

In [17]:
df['new'] = df['X'] + df['Y']

In [18]:
df

X         Y         Z       new
A -0.079689  0.330638  0.391180  0.250949
B  1.047661 -0.144868  0.201546  0.902793
C  0.204755  1.294356  1.425724  1.499111

In [22]:
df.drop('B')

X         Y         Z       new
A -0.079689  0.330638  0.391180  0.250949
C  0.204755  1.294356  1.425724  1.499111

In [28]:
df2 = pd.DataFrame(rd.randn(10,3), columns = ['X', 'Y', 'Z'])

In [34]:
df2

X         Y         Z
0  0.403753  1.194072  0.091188
1 -1.386241  2.024403  0.581746
2 -0.445336  0.546302 -1.824941
3  0.148486 -1.982062 -0.469432
4  0.596770  0.093637  1.235817
5  1.517109  1.332685  0.845896
6 -0.474046 -0.358245 -1.823163
7 -1.050213 -0.129483  0.941938
8  0.105148 -1.017748  1.269999
9 -0.754582 -0.404445  1.328423

In [40]:
df2.loc[range(2,6), ['X', 'Z']]

X         Z
2 -0.445336 -1.824941
3  0.148486 -0.469432
4  0.596770  1.235817
5  1.517109  0.845896

In [45]:
a = range(20)
a
type(a)

range

In [48]:
df2 

X         Y         Z
0  0.403753  1.194072  0.091188
1 -1.386241  2.024403  0.581746
2 -0.445336  0.546302 -1.824941
3  0.148486 -1.982062 -0.469432
4  0.596770  0.093637  1.235817
5  1.517109  1.332685  0.845896
6 -0.474046 -0.358245 -1.823163
7 -1.050213 -0.129483  0.941938
8  0.105148 -1.017748  1.269999
9 -0.754582 -0.404445  1.328423

In [50]:
temp = df2[df2['Y'] > 0]

In [51]:
type(temp)

pandas.core.frame.DataFrame

In [52]:
temp.to_excel('temp.xlsx')

In [56]:
temp.to_csv('temp.csv')

In [54]:
from numpy import genfromtxt

In [57]:
np_csv = genfromtxt('temp.csv', delimiter=',')

In [66]:
np_csv

array([[        nan,         nan,         nan,         nan],
       [ 0.        ,  0.40375337,  1.19407213,  0.09118775],
       [ 1.        , -1.38624113,  2.02440308,  0.58174631],
       [ 2.        , -0.44533551,  0.5463019 , -1.82494075],
       [ 4.        ,  0.5967697 ,  0.09363737,  1.23581652],
       [ 5.        ,  1.51710883,  1.33268451,  0.84589557]])

In [59]:
type(np_csv)

numpy.ndarray

In [60]:
import numpy as np

In [68]:
np.delete(np_csv, 0, 0)

array([[ 0.        ,  0.40375337,  1.19407213,  0.09118775],
       [ 1.        , -1.38624113,  2.02440308,  0.58174631],
       [ 2.        , -0.44533551,  0.5463019 , -1.82494075],
       [ 4.        ,  0.5967697 ,  0.09363737,  1.23581652],
       [ 5.        ,  1.51710883,  1.33268451,  0.84589557]])

In [69]:
np_csv = np.delete(np.delete(np_csv, 0, 0), 0, 1)

In [70]:
np_csv

array([[ 0.40375337,  1.19407213,  0.09118775],
       [-1.38624113,  2.02440308,  0.58174631],
       [-0.44533551,  0.5463019 , -1.82494075],
       [ 0.5967697 ,  0.09363737,  1.23581652],
       [ 1.51710883,  1.33268451,  0.84589557]])